I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/front_page.rpy", line 275, in <module>
WindowsError: [Error 2] 

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "launcher/game/front_page.rpyc", line 265, in script
  File "D:\renpy-6.99.14.1-sdk\renpy\ast.py", line 848, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-6.99.14.1-sdk\renpy\python.py", line 1812, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/front_page.rpy", line 275, in <module>
  File "D:\renpy-6.99.14.1-sdk\jedit\jEdit.edit.py", line 39, in end
    subprocess.Popen(self.arguments)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 710, in __init__
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/subprocess.py", line 958, in _execute_child
WindowsError: [Error 2] 

Windows-8-6.2.9200
Ren'Py 6.99.14.1.3218
Ren'Py Launcher 6.99.14.1.3218
Thu Apr 04 21:05:48 2024
